### ISSUE TITLE
problems installing

### ISSUE THREAD

**Issue by J261** [damphat/crc-itu#2]
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'crc-itu' ]
2 info using npm@3.3.12
3 info using node@v5.3.0
4 verbose config Skipping project config: C:\Users\Jorge/.npmrc. (matches userconfig)
5 silly loadCurrentTree Starting
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 silly fetchPackageMetaData crc-itu
9 silly fetchNamedPackageData crc-itu
10 silly mapToRegistry name crc-itu
11 silly mapToRegistry using default registry
12 silly mapToRegistry registry https://registry.npmjs.org/
13 silly mapToRegistry uri https://registry.npmjs.org/crc-itu
14 verbose request uri https://registry.npmjs.org/crc-itu
15 verbose request no auth needed
16 info attempt registry request try #1 at 23:52:29
17 verbose request id 3cfd5e9f7d4d7289
18 verbose etag "DUBE66B0II7ARSVXM0A89KHDA"
19 http request GET https://registry.npmjs.org/crc-itu
20 http 304 https://registry.npmjs.org/crc-itu
21 verbose headers { date: 'Thu, 06 Oct 2016 04:52:33 GMT',
21 verbose headers   via: '1.1 varnish',
21 verbose headers   'cache-control': 'max-age=300',
21 verbose headers   etag: '"DUBE66B0II7ARSVXM0A89KHDA"',
21 verbose headers   age: '46',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'x-served-by': 'cache-dfw1828-DFW',
21 verbose headers   'x-cache': 'HIT',
21 verbose headers   'x-cache-hits': '1',
21 verbose headers   'x-timer': 'S1475729553.361069,VS0,VE0',
21 verbose headers   vary: 'Accept-Encoding' }
22 silly get cb [ 304,
22 silly get   { date: 'Thu, 06 Oct 2016 04:52:33 GMT',
22 silly get     via: '1.1 varnish',
22 silly get     'cache-control': 'max-age=300',
22 silly get     etag: '"DUBE66B0II7ARSVXM0A89KHDA"',
22 silly get     age: '46',
22 silly get     connection: 'keep-alive',
22 silly get     'x-served-by': 'cache-dfw1828-DFW',
22 silly get     'x-cache': 'HIT',
22 silly get     'x-cache-hits': '1',
22 silly get     'x-timer': 'S1475729553.361069,VS0,VE0',
22 silly get     vary: 'Accept-Encoding' } ]
23 verbose etag https://registry.npmjs.org/crc-itu from cache
24 verbose get saving crc-itu to C:\Users\Jorge\AppData\Roaming\npm-cache\registry.npmjs.org\crc-itu\.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 silly resolveWithNewModule crc-itu@0.1.0 checking installable status
38 silly cache add args [ 'crc-itu', null ]
39 verbose cache add spec crc-itu
40 silly cache add parsed spec Result {
40 silly cache add   raw: 'crc-itu',
40 silly cache add   scope: null,
40 silly cache add   name: 'crc-itu',
40 silly cache add   rawSpec: '',
40 silly cache add   spec: '*',
40 silly cache add   type: 'range' }
41 silly addNamed crc-itu@*
42 verbose addNamed "*" is a valid semver range for crc-itu
43 silly addNameRange { name: 'crc-itu', range: '*', hasData: false }
44 silly mapToRegistry name crc-itu
45 silly mapToRegistry using default registry
46 silly mapToRegistry registry https://registry.npmjs.org/
47 silly mapToRegistry uri https://registry.npmjs.org/crc-itu
48 verbose addNameRange registry:https://registry.npmjs.org/crc-itu not in flight; fetching
49 verbose get https://registry.npmjs.org/crc-itu not expired, no request
50 silly addNameRange number 2 { name: 'crc-itu', range: '*', hasData: true }
51 silly addNameRange versions [ 'crc-itu', [ '0.0.1', '0.0.2', '0.1.0' ] ]
52 silly addNamed crc-itu@0.1.0
53 verbose addNamed "0.1.0" is a plain semver version for crc-itu
54 silly cache afterAdd crc-itu@0.1.0
55 verbose afterAdd C:\Users\Jorge\AppData\Roaming\npm-cache\crc-itu\0.1.0\package\package.json not in flight; writing
56 verbose afterAdd C:\Users\Jorge\AppData\Roaming\npm-cache\crc-itu\0.1.0\package\package.json written
57 silly loadAllDepsIntoIdealTree Finishing
58 silly idealTree:prePrune Jorge
58 silly idealTree:prePrune ├── bignumber.js@2.3.0
58 silly idealTree:prePrune ├── core-util-is@1.0.2
58 silly idealTree:prePrune ├── crc-itu@0.1.0
58 silly idealTree:prePrune ├── inherits@2.0.1
58 silly idealTree:prePrune ├── isarray@0.0.1
58 silly idealTree:prePrune ├── mysql@2.11.1
58 silly idealTree:prePrune ├── readable-stream@1.1.14
58 silly idealTree:prePrune ├── sqlstring@2.0.1
58 silly idealTree:prePrune └── string_decoder@0.10.31
59 silly loadIdealTree Finishing
60 silly currentTree Jorge
60 silly currentTree ├── bignumber.js@2.3.0
60 silly currentTree ├── core-util-is@1.0.2
60 silly currentTree ├── inherits@2.0.1
60 silly currentTree ├── isarray@0.0.1
60 silly currentTree ├── mysql@2.11.1
60 silly currentTree ├── readable-stream@1.1.14
60 silly currentTree ├── sqlstring@2.0.1
60 silly currentTree └── string_decoder@0.10.31
61 silly idealTree Jorge
61 silly idealTree ├── bignumber.js@2.3.0
61 silly idealTree ├── core-util-is@1.0.2
61 silly idealTree ├── crc-itu@0.1.0
61 silly idealTree ├── inherits@2.0.1
61 silly idealTree ├── isarray@0.0.1
61 silly idealTree ├── mysql@2.11.1
61 silly idealTree ├── readable-stream@1.1.14
61 silly idealTree ├── sqlstring@2.0.1
61 silly idealTree └── string_decoder@0.10.31
62 silly generateActionsToTake Starting
63 silly install generateActionsToTake
64 silly generateActionsToTake Finishing
65 silly diffTrees action count 1
66 silly diffTrees add crc-itu@0.1.0
67 silly decomposeActions action count 8
68 silly decomposeActions fetch crc-itu@0.1.0
69 silly decomposeActions extract crc-itu@0.1.0
70 silly decomposeActions preinstall crc-itu@0.1.0
71 silly decomposeActions build crc-itu@0.1.0
72 silly decomposeActions install crc-itu@0.1.0
73 silly decomposeActions postinstall crc-itu@0.1.0
74 silly decomposeActions test crc-itu@0.1.0
75 silly decomposeActions finalize crc-itu@0.1.0
76 silly executeActions Starting
77 silly install executeActions
78 silly doSerial global-install 0
79 silly doParallel fetch 1
80 verbose lock using C:\Users\Jorge\AppData\Roaming\npm-cache\_locks\staging-f763981ed19bd0e9.lock for C:\Users\Jorge\node_modules\.staging
81 silly doParallel extract 1
82 silly extract crc-itu@0.1.0
83 verbose unbuild node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f
84 silly gentlyRm C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f is being purged from base C:\Users\Jorge
85 verbose gentlyRm don't care about contents; nuking C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f
86 verbose tar unpack C:\Users\Jorge\AppData\Roaming\npm-cache\crc-itu\0.1.0\package.tgz
87 verbose tar unpacking to C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f
88 silly gentlyRm C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f is being purged
89 verbose gentlyRm don't care about contents; nuking C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f
90 silly gunzTarPerm modes [ '777', '666' ]
91 silly gunzTarPerm extractEntry package.json
92 silly gunzTarPerm extractEntry .npmignore
93 silly gunzTarPerm extractEntry README.md
94 silly gunzTarPerm extractEntry index.js
95 silly gunzTarPerm extractEntry test.js
96 silly gunzTarPerm extractEntry .travis.yml
97 silly gunzTarPerm extractEntry binding.gyp
98 silly gunzTarPerm extractEntry lib/crc-itu.cc
99 silly doParallel preinstall 1
100 silly preinstall crc-itu@0.1.0 C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f
101 info lifecycle crc-itu@0.1.0~preinstall: crc-itu@0.1.0
102 silly lifecycle crc-itu@0.1.0~preinstall: no script for preinstall, continuing
103 silly doReverseSerial remove 0
104 silly doSerial move 0
105 silly doSerial finalize 1
106 silly finalize C:\Users\Jorge\node_modules\crc-itu
107 silly doSerial build 1
108 silly build crc-itu@0.1.0
109 info linkStuff crc-itu@0.1.0
110 silly linkStuff crc-itu@0.1.0 has C:\Users\Jorge\node_modules as its parent node_modules
111 verbose linkBins crc-itu@0.1.0
112 verbose linkMans crc-itu@0.1.0
113 silly doSerial global-link 0
114 silly doParallel update-linked 0
115 silly doSerial install 1
116 silly install crc-itu@0.1.0 C:\Users\Jorge\node_modules\.staging\crc-itu-df7779b4f3c5d7dde02a3d529251119f
117 info lifecycle crc-itu@0.1.0~install: crc-itu@0.1.0
118 verbose lifecycle crc-itu@0.1.0~install: unsafe-perm in lifecycle true
119 verbose lifecycle crc-itu@0.1.0~install: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Jorge\node_modules\crc-itu\node_modules\.bin;C:\Users\Jorge\node_modules\.bin;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Common Files\Intel\Shared Files\cpp\bin\Intel64;C:\PROGRAM FILES\BROADCOM\BROADCOM 802.11 NETWORK ADAPTER;C:\PROGRAM FILES (X86)\INTEL\ICLS CLIENT\;C:\PROGRAM FILES\INTEL\ICLS CLIENT\;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\DAL;C:\PROGRAM FILES\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\IPT;C:\PROGRAM FILES (X86)\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\DAL;C:\PROGRAM FILES (X86)\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\IPT;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X86;C:\PROGRAM FILES (X86)\INTEL\OPENCL SDK\2.0\BIN\X64;C:\PROGRAM FILES\SONY\VAIO IMPROVEMENT;C:\PROGRAM FILES (X86)\SONY\VAIO BIOS DATA TRANSFER UTILITY\;C:\PROGRAM FILES (X86)\SONY\VAIO STARTUP SETTING TOOL;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\DAL;C:\PROGRAM FILES\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\IPT;C:\PROGRAM FILES (X86)\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\DAL;C:\PROGRAM FILES (X86)\INTEL\INTEL(R) MANAGEMENT ENGINE COMPONENTS\IPT;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\Program Files (x86)\Skype\Phone\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Program Files\TortoiseHg\;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\opencv\build\x64\vc14\bin;C:\Program Files\OpenVPN\bin;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\ManagementStudio\;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\120\DTS\Binn\;C:\Program Files\Microsoft SQL Server\120\DTS\Binn\;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Users\Jorge\AppData\Roaming\npm;C:\Users\Jorge\AppData\Roaming\Composer\vendor\bin
120 verbose lifecycle crc-itu@0.1.0~install: CWD: C:\Users\Jorge\node_modules\crc-itu
121 silly lifecycle crc-itu@0.1.0~install: Args: [ '/d /s /c', 'node-gyp rebuild' ]
122 silly lifecycle crc-itu@0.1.0~install: Returned: code: 1  signal: null
123 info lifecycle crc-itu@0.1.0~install: Failed to exec install script
124 verbose unlock done using C:\Users\Jorge\AppData\Roaming\npm-cache\_locks\staging-f763981ed19bd0e9.lock for C:\Users\Jorge\node_modules\.staging
125 silly rollbackFailedOptional Starting
126 silly rollbackFailedOptional Finishing
127 silly runTopLevelLifecycles Starting
128 silly runTopLevelLifecycles Finishing
129 silly install printInstalled
130 warn ENOENT ENOENT: no such file or directory, open 'C:\Users\Jorge\package.json'
131 warn EPACKAGEJSON Jorge No description
132 warn EPACKAGEJSON Jorge No repository field.
133 warn EPACKAGEJSON Jorge No README data
134 warn EPACKAGEJSON Jorge No license field.
135 verbose stack Error: crc-itu@0.1.0 install: `node-gyp rebuild`
135 verbose stack Exit status 1
135 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:232:16)
135 verbose stack     at emitTwo (events.js:87:13)
135 verbose stack     at EventEmitter.emit (events.js:172:7)
135 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
135 verbose stack     at emitTwo (events.js:87:13)
135 verbose stack     at ChildProcess.emit (events.js:172:7)
135 verbose stack     at maybeClose (internal/child_process.js:818:16)
135 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
136 verbose pkgid crc-itu@0.1.0
137 verbose cwd C:\Users\Jorge\Documents\Proyectos\gps-tracker
138 error Windows_NT 6.3.9600
139 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "crc-itu"
140 error node v5.3.0
141 error npm  v3.3.12
142 error code ELIFECYCLE
143 error crc-itu@0.1.0 install: `node-gyp rebuild`
143 error Exit status 1
144 error Failed at the crc-itu@0.1.0 install script 'node-gyp rebuild'.
144 error Make sure you have the latest version of node.js and npm installed.
144 error If you do, this is most likely a problem with the crc-itu package,
144 error not with npm itself.
144 error Tell the author that this fails on your system:
144 error     node-gyp rebuild
144 error You can get their info via:
144 error     npm owner ls crc-itu
144 error There is likely additional logging output above.
145 verbose exit [ 1, true ]

```

**Comment by damphat** [comment]
**crc-itu** is written in C/C++. Please check if you have **node-gyp** and C/C++ Build Tool for your platform.

Read this document carefully:
https://github.com/nodejs/node-gyp
